;(defparameter in *standard-input*)
(defparameter in (open "input.txt"))

(let ((num-tc (read in)))
    (labels ((f ()
                (let* ((a (read in))
                       (b (read in))
                       (c (read in))
                       (p (read in))
                       (q (read in))
                       (r (read in))
                       (total-pops (+ p q r)))
                    (if (or (> (* 2 (+ p b c)) total-pops)
                            (> (* 2 (+ a q c)) total-pops)
                            (> (* 2 (+ a b r)) total-pops))
                        (format t "YES~%")
                        (format t "NO~%")))))
    (loop repeat num-tc do (f))))
