;(defparameter in *standard-input*)
(defparameter in (open "input.txt"))

(let ((num-tc (read in)))
    (labels ((sum-to-n (n)
                (/ (* n (1+ n)) 2))
            (f ()
                (let ((n (read in))
                      (cur 0)
                      (cnt 0)
                      (sum 0))
                    (loop repeat n do (let ((x (read in)))
                                        (cond ((and (= cur 1) (zerop x)) (progn (setf sum (+ sum (sum-to-n cnt)))
                                                                                (setf cnt 0)))
                                              ((= x 1) (incf cnt)))
                                        (setf cur x)))
                    (if (/= cnt 0)
                        (setf sum (+ sum (sum-to-n cnt))))
                    (format t "~D~%" sum))))
    (loop repeat num-tc do (f))))

