;(defparameter in *standard-input*)
(defparameter in (open "input.txt"))

(labels ((check (num cnt)
	   (if (evenp num)
	       (+ 1 cnt)
	       0))
	 (f ()
	   (let* ((n (read in))
		  (k (read in))
		  (cnt 0)
		  (ans "NO"))
	     (loop repeat n do (progn (setq cnt (check (read in) cnt))
				      (if (= cnt k)
					  (setq ans "YES"))))
	     (format t "~S~%" ans))))
  (let ((num-tc (read in)))
    (loop repeat num-tc do (f))))
